version: "3"

services:
  pybott_test:
    build: ./pybott_test
    container_name : pybott_test
    restart: always
    environment:
      - APP_NAME=pybott_test
    expose:
      - 8080
  
  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"